# Generated by Django 5.2.8 on 2025-11-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('bmi', models.FloatField()),
                ('glucose_level', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('family_history', models.BooleanField()),
                ('exercise_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6)),
                ('outcome', models.BooleanField()),
            ],
        ),
    ]
